nama: FreeRDP

pada: alur kerja_dispatch

pekerjaan:
  membangun:

    berjalan-on: windows-terbaru
    menit-waktu habis: 9999

    Langkah:
    - Nama : Download Ngrok.
      lari: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/MichaelJorky/Free_RDP_Ngrok/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/MichaelJorky/Free_RDP_Ngrok/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/MichaelJorky/Free_RDP_Ngrok/main/wallpaper.bat -OutFile wallpaper.bat
    - Nama : Mengekstrak File Ngrok.
      jalankan: Perluas-Arsip ngrok.zip
    - nama: Menghubungkan ke akun Ngrok Anda.
      jalankan: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      lingkungan:
        NGROK_AUTH_TOKEN: ${{ rahasia.NGROK_AUTH_TOKEN }}
    - nama: Mengaktifkan akses RDP.
      lari: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-nama "fDenyTSConnections" -Nilai 0
        Aktifkan-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1
        salin wallpaper.jpg D:\a\wallpaper.jpg
        salin wallpaper.bat D:\a\wallpaper.bat
    - nama: Membuat Terowongan.
      jalankan: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - nama: Menghubungkan ke RDP Anda.
      jalankan: cmd /c start.bat
    - nama: RDP sudah siap!
      lari: |
        Invoke-WebRequest https://raw.githubusercontent.com/MichaelJorky/Free_RDP_Ngrok/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
